# Generated by Django 2.1.2 on 2018-10-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CDS_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('titleShort', models.CharField(max_length=10)),
                ('created_on', models.IntegerField(default=1538580711)),
                ('updated_on', models.IntegerField(default=1538580711)),
            ],
        ),
    ]
