# Generated by Django 2.1.2 on 2018-10-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cds_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cds_model',
            name='created_on',
            field=models.IntegerField(default=1538581273),
        ),
        migrations.AlterField(
            model_name='cds_model',
            name='updated_on',
            field=models.IntegerField(default=1538581273),
        ),
    ]
