# Generated by Django 2.1.2 on 2018-10-10 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corps_app', '0005_auto_20181010_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members_app',
            name='cds_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cds_app.cds_model'),
        ),
        migrations.AlterField(
            model_name='members_app',
            name='created_on',
            field=models.IntegerField(default=1539185543),
        ),
        migrations.AlterField(
            model_name='members_app',
            name='field_office_signature_date',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='members_app',
            name='updated_on',
            field=models.IntegerField(default=1539185543),
        ),
    ]
