# Generated by Django 2.1.2 on 2018-10-10 21:01

from django.db import migrations, models
import django.db.models.deletion
import nysc_datacenter_backend.formatChecker
import nysc_datacenter_backend.miscelaneous


class Migration(migrations.Migration):

    dependencies = [
        ('corps_app', '0006_auto_20181010_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members_app',
            name='cds_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cds_app.cds_model'),
        ),
        migrations.AlterField(
            model_name='members_app',
            name='cm_signature',
            field=models.ImageField(blank=True, upload_to=nysc_datacenter_backend.miscelaneous.RandomFileName('images'), validators=[nysc_datacenter_backend.formatChecker.file_size]),
        ),
        migrations.AlterField(
            model_name='members_app',
            name='cover',
            field=models.ImageField(blank=True, upload_to=nysc_datacenter_backend.miscelaneous.RandomFileName('images'), validators=[nysc_datacenter_backend.formatChecker.file_size]),
        ),
        migrations.AlterField(
            model_name='members_app',
            name='created_on',
            field=models.IntegerField(default=1539205317),
        ),
        migrations.AlterField(
            model_name='members_app',
            name='field_office_signature',
            field=models.ImageField(blank=True, upload_to=nysc_datacenter_backend.miscelaneous.RandomFileName('images'), validators=[nysc_datacenter_backend.formatChecker.file_size]),
        ),
        migrations.AlterField(
            model_name='members_app',
            name='updated_on',
            field=models.IntegerField(default=1539205317),
        ),
    ]
