# Generated by Django 2.1.2 on 2018-10-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='section_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=50)),
                ('batch', models.CharField(max_length=2)),
                ('created_on', models.IntegerField(default=1538582390)),
            ],
        ),
        migrations.DeleteModel(
            name='section_app',
        ),
    ]
