# Generated by Django 2.1.2 on 2018-10-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section_app', '0007_auto_20181010_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section_model',
            name='created_on',
            field=models.IntegerField(default=1539185543),
        ),
    ]
