# Generated by Django 2.1.2 on 2018-10-10 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section_app', '0008_auto_20181010_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section_model',
            name='created_on',
            field=models.IntegerField(default=1539205317),
        ),
    ]
